apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: akmebank-ui
spec:
  rules:
  - host: akmebank-app.cluster-ingress-subdomain
    http:
      paths:
      - backend:
          serviceName: akmebank-ui-cip
          servicePort: 80
        path: /
  tls:
  - hosts:
    - akmebank-app-app.cluster-ingress-subdomain
    secretName: cluster-ingress-secret
